# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-25 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownwr_name', models.CharField(max_length=100, null=True)),
                ('ownwr_mob', models.CharField(max_length=100, null=True)),
                ('ownwr_add', models.CharField(max_length=100, null=True)),
                ('rfid_no', models.CharField(max_length=12, null=True)),
                ('vehicle_no', models.CharField(max_length=100, null=True)),
                ('vehicle_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('entry_time', models.CharField(max_length=100, null=True)),
                ('entry_date', models.DateField(auto_now=True, null=True)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TrackerApp.Vehicle_info')),
            ],
        ),
    ]
