# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine_of_vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(max_length=100, null=True)),
                ('fine', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle_status',
            name='fine',
            field=models.IntegerField(null=True),
        ),
    ]
