# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-25 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0002_auto_20190325_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_status',
            name='entry_date',
            field=models.DateField(null=True),
        ),
    ]
