# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackerApp', '0003_auto_20190325_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_status',
            name='entry_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
